### ISSUE TITLE
The preprocessed data is missing.

### ISSUE THREAD

**Issue by Maggie22** [KelestZ/ICW-GANs#1]
Hi! This work is great and I'm really interested in it! But I cannot open the page of preprocessed data. It is now "404 Not Found".
Could you update the URL please?
I'll really appreciate that :-)

**Comment by KelestZ** [comment]
Sorry for the late reply and thanks for your interest in our work. Currently, we don't have the preprocessed data anymore. Nonetheless, you may download the original data and process it by yourself which is quite convenient. Please ping if there is any other questions and I'm willing to help.

**Comment by KelestZ** [comment]
> Hi! This work is great and I'm really interested in it! But I cannot open the page of preprocessed data. It is now "404 Not Found".
> Could you update the URL please?
> I'll really appreciate that :-)

Sorry for the late reply and thanks for your interest in our work. Currently, we don't have the preprocessed data anymore. Nonetheless, you may download the original data and process it by yourself which is quite convenient. Please ping if there is any other questions and I'm willing to help.

**Comment by Maggie22** [comment]
OK, I get it. Thanks for your response!
